[package]
name = "wavs-types"
version = "0.3.0-rc1"
description = "WAVS Types"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = true

[dependencies]
serde = { workspace = true }
wasm-pkg-client = { workspace = true }
wasm-pkg-common = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
const-hex = { workspace = true }
alloy-primitives = { workspace = true }
cosmwasm-std = { workspace = true }
layer-climb-address = { workspace = true }