[package]
name = "wavs-types"
version = "0.3.0"
description = "WAVS Types"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = true

[features]
default = ["solidity-rpc"]
solidity-rpc = []

[dependencies]
anyhow = { workspace = true }
cron = { workspace = true, features = ["serde"] }
chrono = { workspace = true }
serde = { workspace = true }
wasm-pkg-client = { workspace = true }
wasm-pkg-common = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
const-hex = { workspace = true }
cosmwasm-std = { workspace = true }
layer-climb-address = { workspace = true }
bincode = {workspace = true}
ripemd = {workspace = true}
alloy = {workspace = true}
# alloy-primitives = { workspace = true }
# alloy-sol-macro = { workspace = true }
# alloy-sol-types = { workspace = true }
# alloy-provider = { workspace = true, optional = true}
# alloy-contract = { workspace = true, optional = true}
