# the allowed cors origins. Default is empty list.
cors_allowed_origins = [
  "https://lay3rlabs.github.io/*",
  "http://127.0.0.1:*",
  "http://127.0.0.1:*",
]

tasks_quorum = 1

[chains.eth.local]
chain_id = "31337"
ws_endpoint = "ws://127.0.0.1:8545"
http_endpoint = "http://127.0.0.1:8545"

[chains.eth.e2elocal2]
chain_id = "31338"
ws_endpoint = "ws://127.0.0.1:8645"
http_endpoint = "http://127.0.0.1:8645"
