# the allowed cors origins. Default is empty list.
cors_allowed_origins = [
  "https://lay3rlabs.github.io/*",
  "http://localhost:*",
  "http://127.0.0.1:*",
]

ws_endpoint = "ws://localhost:8645"
http_endpoint = "http://localhost:8645"
tasks_quorum = 1

# This matches what is in the wavs.toml, just without aggregator url
# ideally wee just use that? (hard link or something here within the aggregator)
[chains.eth.local]
chain_id = "31337"
ws_endpoint = "ws://localhost:8545"
http_endpoint = "http://localhost:8545"

[chains.eth.e2elocal2]
chain_id = "31338"
ws_endpoint = "ws://localhost:8645"
http_endpoint = "http://localhost:8645"
