[package]
name = "wavs-aggregator"
version = "0.3.0-alpha1"
description = "WAVS Aggregator Server"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
wavs-types = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
figment = { workspace = true }
dirs = { workspace = true }
thiserror = { workspace = true }
tower-http = { workspace = true }
wildmatch = { workspace = true }
alloy = { workspace = true }
wavs = { workspace = true }
utils = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
wavs-cli = { workspace = true }
temp-env = { workspace = true }
serde_json = { workspace = true }
