[package]
name = "wavs-aggregator"
description = "WAVS Aggregator Server"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
wavs-types = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tower-http = { workspace = true }
wildmatch = { workspace = true }
alloy-contract = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-primitives = { workspace = true }
alloy-sol-macro = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-provider = { workspace = true }
utils = { workspace = true }
tempfile = { workspace = true }
redb = { workspace = true }

[dev-dependencies]
