[package]
name = "aggregator"
description = "Lay3r Labs WAVS Aggregator Server"
edition.workspace = true
version = "0.1.0-rc1"
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
dotenvy = { workspace = true }
ctrlc = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
figment = { workspace = true }
dirs = { workspace = true }
thiserror = { workspace = true }
tower-http = { workspace = true }
wildmatch = { workspace = true }
alloy = { workspace = true }

wavs = { workspace = true }
utils = { workspace = true }

[dev-dependencies]
temp-env = { workspace = true }
alloy = { version = "0.6.4", features = ["full", "node-bindings"] }
serde_json = { workspace = true }
