[package]
name = "aggregator"
description = "Lay3r Labs WAVS Aggregator Server"
edition.workspace = true
version = "0.2.0-rc1"
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
dotenvy = { workspace = true }
ctrlc = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
layer-climb = { workspace = true }
figment = { workspace = true}
dirs = { workspace = true }
thiserror = { workspace = true }
tower-http = { workspace = true }
wildmatch = { workspace = true }
alloy = { workspace = true }

wavs = { workspace = true }
utils = { workspace = true }