[package]
name = "wavs-wasi-chain"
version = "0.3.0-alpha1"
description = "WAVS WASI Chain helpers"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = true 

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
layer-climb = { workspace = true }
wstd = { workspace = true }
wasi = { workspace = true }
wit-bindgen-rt = {workspace = true}
alloy-primitives = { workspace = true }
alloy-sol-types = {workspace = true }
alloy-json-rpc = {workspace = true} 
alloy-provider = {workspace = true} 
alloy-transport-http = {workspace = true} 
alloy-transport = {workspace = true}
alloy-rpc-client = {workspace = true} 
async-trait = {workspace = true} 
cfg-if = {workspace = true} 
tower-service = {workspace = true} 
futures-utils-wasm = {workspace = true}

[lib]
crate-type = ["rlib", "cdylib"]
