global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'

receivers:
  - name: 'default'
    # No configs - just displays in Alertmanager UI
    # Add your notification configs here later:
    # slack_configs:
    #   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    # email_configs:
    #   - to: 'your-email@example.com'