[profile.default]
libs = ["lib", "lib/eigenlayer-middleware/lib"]
remappings = [
  "@eigenlayer/contracts=lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/contracts",
  "@eigenlayer/middleware=lib/eigenlayer-middleware",
  "@eigenlayer/test=lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/test",
  "@openzeppelin-upgrades/=lib/eigenlayer-middleware/lib/openzeppelin-contracts-upgradeable/",
  "@openzeppelin/=lib/eigenlayer-middleware/lib/openzeppelin-contracts/",

]
git_protocol = "ssh"
src = "contracts"
fs_permissions = [{ access = "read-write", path = "./" }]
via_ir = true
