[profile.default]
remappings = [
    "@eigenlayer/contracts=lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/contracts",
    "@eigenlayer/middleware=lib/eigenlayer-middleware",
    "@eigenlayer/test=lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/test",
]
git_protocol = "ssh"
src = "contracts"
fs_permissions = [{ access = "read-write", path = "./" }]
via_ir = true
