[package]
name = "simple-example"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
layer-cosmwasm = {workspace = true}
cosmwasm-std = {workspace = true}
anyhow = {workspace = true} 
cw-storage-plus = {workspace = true} 
cw2 = {workspace = true} 
cosmwasm-schema = {workspace = true}
hex = {workspace = true}
