[package]
name = "wavs-dev-tools"
description = "WAVS Types"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
alloy-signer-local = { workspace = true }
wavs-types = { workspace = true }
wavs-cli = { workspace = true }
utils = { workspace = true }
clap = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
