# these values can be overriden by environment variables
# by following the pattern MATIC_<UPPERCASE_KEY>
# so for example, the key `port` can be overriden by setting the environment variable `MATIC_PORT`

# the port on which the server will listen. Default is 8000
# port = 9000

# The log level, in the format of tracing directives.
# See https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#directives for more information
# When overriding this in the environment, use a comma-separated list in a single string
# e.g. MATIC_LOG_LEVEL="info, wasmatic=debug"
log_level = ["info", "wasmatic=debug"]