[package]
name = "mock-service-handler"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wavs-types ={ workspace = true }
cosmwasm-std = {workspace = true}
anyhow = {workspace = true} 
cw-storage-plus = {workspace = true} 
cw2 = {workspace = true} 
cosmwasm-schema = {workspace = true}
const-hex = {workspace = true}