[package]
name = "mock-service-handler"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# The workspace `wavs-types` has features, we need to disable them, overriding with `worksace = true` doesn't work
wavs-types = { path = "../../../../packages/types", default-features = false, features = ["cosmwasm"] }
cosmwasm-std = {workspace = true}
anyhow = {workspace = true} 
cw-storage-plus = {workspace = true} 
cw2 = {workspace = true} 
cosmwasm-schema = {workspace = true}
const-hex = {workspace = true}