// https://docs.rs/wasmtime/latest/wasmtime/component/macro.bindgen.html#options-reference

use wasmtime::component::bindgen;

bindgen!({
    world: "wavs-world",
    path: "../../wit-definitions/operator/wit",
    with: {
        "wasi:keyvalue/store.bucket": crate::backend::wasi_keyvalue::bucket_keys::KeyValueBucket,
        "wasi:keyvalue/atomics.cas": crate::backend::wasi_keyvalue::atomics::KeyValueCas,
    },
    exports: {
        default: async,
    },
});

/// Bindings for the legacy world (components that only export `run`, without the agent interface).
/// Used by execute_legacy for components compiled before the continuation engine was introduced.
///
/// We re-use the same Rust types already generated for `wavs-world` by mapping them via `with:`.
/// This avoids duplicating types and allows the same `TriggerAction` / `WasmResponse` values
/// to flow through both the agent and legacy paths without any conversion.
#[allow(clippy::all, dead_code)]
pub mod legacy {
    wasmtime::component::bindgen!({
        world: "wavs-legacy-world",
        path: "../../wit-definitions/operator/wit",
        with: {
            "wasi:keyvalue/store.bucket": crate::backend::wasi_keyvalue::bucket_keys::KeyValueBucket,
            "wasi:keyvalue/atomics.cas": crate::backend::wasi_keyvalue::atomics::KeyValueCas,
            // Reuse the types generated by the main wavs-world bindgen to avoid type duplication.
            "wavs:operator/input": super::wavs::operator::input,
            "wavs:operator/output": super::wavs::operator::output,
        },
        exports: {
            default: async,
        },
    });
}
