package lay3r:avs@0.0.2;

interface task-queue-types {
  record input {
    timestamp: u64,
    /// serialized json, avs wasi and lay3r contract must agree on the types
    /// the runner is agnostic to the data format
    request: string,
  }

  record output {
    /// serialized json, avs wasi and lay3r contract must agree on the types
    /// the runner is agnostic to the data format
    response: string,
  }

  type error = string;
}

world task-queue {
  import wasi:io/poll@0.2.0;
  import wasi:clocks/monotonic-clock@0.2.0;
  import wasi:io/error@0.2.0;
  import wasi:io/streams@0.2.0;
  import wasi:http/types@0.2.0;
  import wasi:http/outgoing-handler@0.2.0;
  import task-queue-types;
  use task-queue-types.{input, output, error};

  export run-task: func(request: input) -> result<output, error>;
}
