package lay3r:avs@0.3.0;

interface types {
  /// serialized json, avs wasi and lay3r contract must agree on the types
  /// the runner is agnostic to the data format
  type serialized-json = list<u8>;

  record task-queue-input {
    timestamp: u64,
    request: serialized-json,
  }

  type error = string;
  type output = result<serialized-json, error>;
}

world task-queue {
  import wasi:io/poll@0.2.0;
  import wasi:clocks/monotonic-clock@0.2.0;
  import wasi:io/error@0.2.0;
  import wasi:io/streams@0.2.0;
  import wasi:http/types@0.2.0;
  import wasi:http/outgoing-handler@0.2.0;
  use types.{task-queue-input, output};

  export run-task: func(request: task-queue-input) -> output;
}

world cron-job {
  import wasi:io/poll@0.2.0;
  import wasi:clocks/monotonic-clock@0.2.0;
  import wasi:io/error@0.2.0;
  import wasi:io/streams@0.2.0;
  import wasi:http/types@0.2.0;
  import wasi:http/outgoing-handler@0.2.0;
  use types.{output};

  export run-cron: func() -> output;
}

world eth-event {
  import wasi:io/poll@0.2.0;
  import wasi:clocks/monotonic-clock@0.2.0;
  import wasi:io/error@0.2.0;
  import wasi:io/streams@0.2.0;
  import wasi:http/types@0.2.0;
  import wasi:http/outgoing-handler@0.2.0;

  // An alloy log can be recreated with the info here 
  // block height is extra
  record eth-log {
    // the address that emitted an event
    address: list<u8>,
    // the raw log topics that can be decoded into an event
    log-topics: list<list<u8>>,
    // the raw log data that can be decoded into an event
    log-data: list<u8>,
  }

  type eth-output = list<u8>;

  export process-eth-event: func(log: eth-log) -> result<eth-output, string>;
}