package lay3r:avs@0.3.0;

interface types {
  /// serialized json, avs wasi and lay3r contract must agree on the types
  /// the runner is agnostic to the data format
  type serialized-json = list<u8>;

  record task-queue-input {
    timestamp: u64,
    request: serialized-json,
  }

  type error = string;
  type output = result<serialized-json, error>;
}

world task-queue {
  import wasi:io/poll@0.2.0;
  import wasi:clocks/monotonic-clock@0.2.0;
  import wasi:io/error@0.2.0;
  import wasi:io/streams@0.2.0;
  import wasi:http/types@0.2.0;
  import wasi:http/outgoing-handler@0.2.0;
  use types.{task-queue-input, output};

  export run-task: func(request: task-queue-input) -> output;
}

world cron-job {
  import wasi:io/poll@0.2.0;
  import wasi:clocks/monotonic-clock@0.2.0;
  import wasi:io/error@0.2.0;
  import wasi:io/streams@0.2.0;
  import wasi:http/types@0.2.0;
  import wasi:http/outgoing-handler@0.2.0;
  use types.{output};

  export run-cron: func() -> output;
}

world eth-event {
  import wasi:io/poll@0.2.0;
  import wasi:clocks/monotonic-clock@0.2.0;
  import wasi:io/error@0.2.0;
  import wasi:io/streams@0.2.0;
  import wasi:http/types@0.2.0;
  import wasi:http/outgoing-handler@0.2.0;

  record eth-input {
    address: list<u8>,
    block-height: u64,
    event: event,
  }

  record eth-output {
    // should be rlp-encoded
    response: list<u8>,
  }

  // it's up to the component to decode the event using something like alloy
  record event {
    topics: list<list<u8>>,
    data: list<u8>,
  }

  export process-eth-event: func(request: eth-input) -> result<eth-output, string>;
}