[package]
name = "wavs-engine"
description = "WAVS Engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
wavs-types = { workspace = true }
utils = { workspace = true }
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
wasmtime-wasi-http = { workspace = true }
wasmtime-wasi-keyvalue = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
layer-climb = { workspace = true }
alloy-primitives = { workspace = true }
tokio = { workspace = true }
