[package]
name = "wavs-cli"
version = "0.3.0"
description = "WAVS Types"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
wasm-pkg-common = { workspace = true }
wasm-pkg-client = { workspace = true }
wavs-types = { workspace = true }
wavs-engine = { workspace = true }
utils = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
alloy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
const-hex = { workspace = true }
reqwest = { workspace = true }
layer-climb = { workspace = true }
wasmtime = { workspace = true }
tempfile = { workspace = true }
shellexpand = { workspace = true }
uuid = { workspace = true }
cfg-if = { workspace = true }
alloy-json-abi = { workspace = true }
cron = { workspace = true }
chrono = { workspace = true }
