services:
  eigenlayer:
    container_name: eigenlayer_setup
    platform: linux/amd64
    build:
      context: ./docker/eigenlayer
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./.nodes:/root/.nodes
  anvil:
    container_name: anvil
    platform: linux/amd64
    build:
      context: ./docker/ethereum
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 8545