[package]
name = "http-allowed-coingecko"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
edition.rust-version = true
repository.workspace = true

[dependencies]
wit-bindgen-rt = { version = "0.32.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.component]
package = "lay3r-examples:http-allowed-coingecko"
target = "lay3r-examples:http-allow-list@0.1.0"

[package.metadata.component.dependencies]
