[package]
name = "http-allowed-coingecko"
version.workspace = true
authors.workspace = true
edition.workspace = true
edition.rust-version = true
repository.workspace = true
publish = false

[dependencies]
wit-bindgen-rt = { workspace = true }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "lay3r-examples:http-allowed-coingecko"
target = "lay3r-examples:http-allow-list@0.1.0"

[package.metadata.component.dependencies]
