[package]
name = "utils"
version = "0.3.0-rc1"
description = "Internal utils for various packages"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
wavs-types = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
alloy = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
tracing-subscriber = { workspace = true }
rand = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
redb = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }
layer-climb = { workspace = true }
figment = { workspace = true }
dirs = { workspace = true }
dotenvy = { workspace = true }
shellexpand = { workspace = true }
cfg-if = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
temp-env = { workspace = true }
