[package]
name = "utils"
description = "Internal utils for various packages"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[features]
test-utils = ["dep:rand", "dep:bip39"]

[dependencies]
wasm-pkg-client = { workspace = true }
wavs-types = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
redb = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }
layer-climb = { workspace = true }
figment = { workspace = true }
dirs = { workspace = true }
dotenvy = { workspace = true }
shellexpand = { workspace = true }
async-trait = { workspace = true }
const-hex = { workspace = true }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-contract = { workspace = true }
alloy-provider = { workspace = true}
alloy-node-bindings = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-network = { workspace = true }
alloy-transport = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
utoipa = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-jaeger-propagator = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
tracing-opentelemetry = { workspace = true }
url = { workspace = true }
cid = { workspace = true }
reqwest = { workspace = true }
iri-string = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
tempfile = { workspace = true }
rand = { workspace = true, optional = true }
bip39 = { workspace = true, optional = true }
subtle = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
temp-env = { workspace = true }
toml = { workspace = true }
utils = { path = ".", features = ["test-utils"] }
tower = { workspace = true }
