[package]
name = "utils"
description = "Internal utils for various packages"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
wasm-pkg-client = { workspace = true }
wavs-types = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
redb = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }
layer-climb = { workspace = true }
figment = { workspace = true }
dirs = { workspace = true }
dotenvy = { workspace = true }
shellexpand = { workspace = true }
async-trait = { workspace = true }
const-hex= { workspace = true }
alloy-primitives = { workspace = true }
# alloy-sol-macro = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-provider = { workspace = true, features = ["pubsub"] }
alloy-node-bindings = { workspace = true }
# alloy-contract = { workspace = true}
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-network = { workspace = true }
# alloy-json-abi = {workspace = true}
# alloy-json-rpc = {workspace = true}
# alloy-rpc-client = {workspace = true} 
alloy-transport = { workspace = true }
# alloy-transport-http = {workspace = true}
alloy-rpc-types-eth = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
temp-env = { workspace = true }
