on: [pull_request]

name: Basic Checks (Optimized)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUST_VERSION: 1.88.0
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short
  WAVS_SUBMISSION_MNEMONIC: "test test test test test test test test test test test junk"
  WAVS_CLI_EVM_CREDENTIAL: "test test test test test test test test test test test junk"
  WAVS_AGGREGATOR_CREDENTIAL: "test test test test test test test test test test test junk"
  WAVS_COSMOS_SUBMISSION_MNEMONIC: "reward index time stem expire cheap worth fence coil option treat ensure install entry zone mule benefit success remain rebuild inherit eyebrow cluster sheriff"
  WAVS_CLI_COSMOS_MNEMONIC: "reward index time stem expire cheap worth fence coil option treat ensure install entry zone mule benefit success remain rebuild inherit eyebrow cluster sheriff"

jobs:
  get-packages:
    name: Get workspace packages
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - id: packages
        run: |
          PACKAGES=$(cargo metadata --no-deps --format-version 1 | jq -c '[.workspace_members[] | split(" ")[0]]')
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT

  test:
    name: Test ${{ matrix.package }}
    needs: get-packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.get-packages.outputs.packages) }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          prefix-key: v0-${{ matrix.package }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run tests
        run: cargo test -p ${{ matrix.package }} --locked -- --nocapture
        env:
          RUST_LOG: info

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
